# Generated by Django 4.2.7 on 2023-11-15 08:39
""" Migrations for Events"""
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """" the following code shows the migration """

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="clubuser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=30)),
                ("lastname", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=300)),
                ("phone", models.CharField(max_length=25)),
                ("web", models.URLField()),
                ("email", models.EmailField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=100)),
                ("event_date", models.DateTimeField()),
                ("description", models.TextField()),
                ("attendee", models.ManyToManyField(blank=True, to="Events.clubuser")),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Events.venue",
                    ),
                ),
            ],
        ),
    ]
