# Generated by Django 4.2.7 on 2023-11-20 06:49
""" Migration  for Events"""
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """ Migration  for Events"""

    dependencies = [
        ("Events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="attendee",
            field=models.ManyToManyField(to="Events.clubuser"),
        ),
        migrations.AlterField(
            model_name="event",
            name="venue",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="Events.venue",
            ),
            preserve_default=False,
        ),
    ]
