# Generated by Django 4.2.7 on 2023-11-23 07:05
""" Migration  for Events"""
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """ Migration  for Events"""

    dependencies = [
        ("Events", "0002_alter_event_attendee_alter_event_venue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Events.venue"
            ),
        ),
    ]
