# Generated by Django 4.2.7 on 2023-11-23 07:05
"""Migrations for employess"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """ migrations for Employes"""

    dependencies = [
        ("Employes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="myfield",
            field=models.CharField(
                choices=[("green", "green"), ("red", "red")], default=0, max_length=256
            ),
            preserve_default=False,
        ),
    ]
