# Generated by Django 4.2.7 on 2023-11-23 09:02
"""Migrations for Employes"""
from django.db import migrations, models


class Migration(migrations.Migration):
    """ Migrations for Employes"""

    dependencies = [
        ("Employes", "0003_alter_department_myfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="myfield",
            field=models.CharField(
                choices=[("1", "greencolor"), ("2", "redcolor")], max_length=256
            ),
        ),
    ]
